[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
